#!/bin/bash
msg() {
  local _msg="${1-}"
  cat << _EOF_
              $( echo "$_msg" | sed 's/^/( /;s/$/ )/;' )
             ( )
            o
  (^)___(^)
 /  ●  。 ● \\
(      人    )
_EOF_
}

left() {
  cat << _EOF_
  (^)___(^)
 / ● 。 ● \\
(   人     )
_EOF_
}

right() {
  cat << _EOF_
  (^)___(^)
 /  ●  。 ●\\
(      人   )
_EOF_
}

club () {
  cat << _EOF_
          　　　  (クラブに行きたいなあ)
  (^)___(^)　　◯
 /   ● . ● \\
(      人    )
_EOF_
}

pon () {
  cat << _EOF_
  (^)___(^)
/           \\
|   ● . ●   |
\\     人    /
_EOF_
}

main() {
  cmd="${1:-クラブに行きたいなあ}"
  case "$cmd" in
    left)
      left
      ;;
    right)
      right
      ;;
    club)
      club
      ;;
    pon)
      pon
      ;;
    *)
      msg "$cmd"
  esac
}

main "${1+"$@"}"
